#!/usr/bin/env bash
# post-generate-traceability.sh
# Claude Code PostToolUse hook — fires after Edit or Write calls.
# When an artefact generated by /2_content_model through /8_test is created
# or modified, this hook reminds Claude to update the requirements
# traceability section in REQUIREMENTS.md.
#
# Input: JSON on stdin with { tool_name, tool_input: { file_path }, tool_output }
# Output: context string on stdout to inject into conversation.

set -euo pipefail

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Detect artefact types produced by /2_*–/8_* commands
IS_GENERATED=false

case "$FILE_PATH" in
  # /2_content_model artefacts
  *-model*.xml|*content-model*.xml|*-context.xml|*bootstrap-context.xml)
    ARTEFACT_TYPE="content-model"
    IS_GENERATED=true
    ;;
  # /3_web_scripts artefacts
  *.desc.xml|*.get.js|*.get.java|*.post.js|*.post.java|*.get.json.ftl|*.post.json.ftl)
    ARTEFACT_TYPE="web-script"
    IS_GENERATED=true
    ;;
  # /4_rest_api artefacts
  *Controller.java|*Entry.java|*Paging.java|*openapi*.yaml|*openapi*.yml)
    ARTEFACT_TYPE="rest-api"
    IS_GENERATED=true
    ;;
  # /5_behaviours artefacts
  *Behaviour.java|*behavior*.xml|*service-context.xml)
    ARTEFACT_TYPE="behaviour"
    IS_GENERATED=true
    ;;
  # /6_actions artefacts
  *ActionExecuter.java)
    ARTEFACT_TYPE="action"
    IS_GENERATED=true
    ;;
  # /7_docker_compose artefacts
  *compose.yaml|*compose.yml|*docker-compose.yaml|*docker-compose.yml|*Dockerfile)
    ARTEFACT_TYPE="docker-compose"
    IS_GENERATED=true
    ;;
  # /8_test artefacts
  *IT.java|*.postman_collection.json)
    ARTEFACT_TYPE="test"
    IS_GENERATED=true
    ;;
esac

if [ "$IS_GENERATED" = false ]; then
  exit 0
fi

# Check if REQUIREMENTS.md exists in the project
PROJECT_DIR=$(pwd)
REQ_FILE=""
for candidate in "$PROJECT_DIR/REQUIREMENTS.md" "$PROJECT_DIR/docs/REQUIREMENTS.md"; do
  if [ -f "$candidate" ]; then
    REQ_FILE="$candidate"
    break
  fi
done

if [ -z "$REQ_FILE" ]; then
  # No requirements file yet — nothing to update
  exit 0
fi

echo "Artefact of type '$ARTEFACT_TYPE' was written to $FILE_PATH. Update the traceability section in $REQ_FILE to reflect this generated artefact."
exit 0
